services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 8000:8000
    volumes:
      - .:/app

  postgres:
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    healthcheck:
      start_interval: 1s
      start_period: 5s
      test: pg_isready -U postgres -d postgres
    image: postgres
    ports:
      - 5432:5432
    secrets:
      - postgres_password

secrets:
  postgres_password:
    file: postgres_password
