# Generated by Django 5.1.3 on 2024-11-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(unique=True)),
                ("name", models.CharField(blank=True)),
                (
                    "price_group",
                    models.IntegerField(
                        choices=[
                            (0, "unknown"),
                            (1, "lower 50k/person"),
                            (2, "50-100k/person"),
                            (3, "100-200k/person"),
                            (4, "200-500k/person"),
                            (5, "500k-1m/person"),
                            (6, "upper 1m/person"),
                        ],
                    ),
                ),
            ],
        ),
    ]
