on:
  - push
jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: set-image-url
        run: |
          image_url=ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
          echo "image_url=$image_url" >> "$GITHUB_ENV"
      - id: set-image-id
        run: |
          if docker pull ${{ env.image_url }}
          then
            image_id=$(docker image ls -q -f=reference=${{ env.image_url }})
            echo "image_id=$image_id" >> "$GITHUB_ENV"
          fi
      - uses: docker/build-push-action@v6
        with:
          tags: ${{ env.image_url }}
          load: true
          cache-from: type=registry,ref=${{ env.image_url }}:cache
      - id: check-image-id
        run: |
          image_id=$(docker image ls -q -f=reference=${{ env.image_url }})
          if [ "$image_id" != "${{ env.image_id }}" ]
          then
            echo "is_image_rebuilt=true" >> "$GITHUB_ENV"
          fi
      - uses: docker/build-push-action@v6
        if: ${{ env.is_image_rebuilt == 'true' }}
        with:
          tags: ${{ env.image_url }}
          push: true
          cache-to: type=registry,ref=${{ env.image_url }}:cache
