on:
  - push
env:
  image_url: ghcr.io/${{ github.repository_owner }}/${{ github.repository }}
jobs:
  build:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: set-image-id
        run: |
          if docker pull ${{ env.image_url }}
          then
            image_id=$(docker image ls -q -f=reference=${{ env.image_url }})
            echo "image_id=$image_id" >> "$GITHUB_ENV"
          fi
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          tags: ${{ env.image_url }}
          load: true
          cache-from: type=registry,ref=${{ env.image_url }}:cache
      - id: check-image-id
        run: |
          image_id=$(docker image ls -q -f=reference=${{ env.image_url }})
          if [ "$image_id" != "${{ env.image_id }}" ]
          then
            echo "is_image_rebuilt=true" >> "$GITHUB_ENV"
          fi
      - uses: docker/build-push-action@v6
        if: ${{ env.is_image_rebuilt == 'true' }}
        with:
          tags: ${{ env.image_url }}
          push: true
          cache-to: type=registry,ref=${{ env.image_url }}:cache
  lint:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: ${{ env.image_url }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - run: ruff check --diff
